server:  port: 8081

spring:
  datasource:    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base
    username: root
    password: root  jpa:    properties:      hibernate:        dialect: org.hibernate.dialect.MySQL5Dialect    hibernate:      ddl-auto: create-drop    show-sql: true